### Get Leaderboard
GET http://127.0.0.1:5000/leaderboard


### Chat + XP Test
POST http://127.0.0.1:5000/chat
Content-Type: application/json

{
  "user_id": 1,
  "message": "Explain normalization in DBMS"
}
